language: php

sudo: false

git:
    depth: 1

php:
    - 5.3
    - 5.4
    - 5.5

env:
    - SYMFONY_VERSION=origin/2.1
    - SYMFONY_VERSION=origin/2.2
    - SYMFONY_VERSION=origin/2.3
    - SYMFONY_VERSION=origin/2.4
    - SYMFONY_VERSION=origin/master

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist

script:
- vendor/bin/phpunit

notifications:
    irc: "irc.freenode.org#noiselabs"
    email:
        - vitor@noiselabs.org
