language: php

php:
    - 5.3
    - 5.4
    - 5.5

env:
    - SYMFONY_VERSION=origin/2.1
    - SYMFONY_VERSION=origin/2.2
    - SYMFONY_VERSION=origin/2.3
    - SYMFONY_VERSION=origin/2.4
    - SYMFONY_VERSION=origin/master

before_script:
  - composer --dev install
  - pip install codecov

script: phpunit

after_success:
  - codecov

notifications:
    irc: "irc.freenode.org#noiselabs"
    email:
        - vitor@noiselabs.org
